### ISSUE TITLE
Failsafe mode on command line

### ISSUE THREAD

**Issue by lavilao** [LostRuins/koboldcpp#1260]
**Describe the Issue**
Hi, thanks for this awesome project, is there a way to use the failsafe mode from the cli? I can use it on the gui but I cant find it on the command line arguments. --noavx2 does not work as it still requires avx.

**Additional Information:**
cpu: celeron n3050
log:
```
.\koboldcpp_nocuda.exe --noavx2 --model .\sha256-40f7094960b6ede829145d102ca79451b364b27d9d8694d4406e002024cff357
***
Welcome to KoboldCpp - Version 1.79.1
No GPU or CPU backend was selected. Trying to assign one for you automatically...
No GPU Backend found...

No GPU backend found, or could not automatically determine GPU layers. Please set it manually.
Attempting to use non-avx2 compatibility library.
Initializing dynamic library: koboldcpp_noavx2.dll
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 1114] Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "koboldcpp.py", line 5009, in <module>
    main(parser.parse_args(),start_server=True)
  File "koboldcpp.py", line 4570, in main
    init_library() # Note: if blas does not exist and is enabled, program will crash.
  File "koboldcpp.py", line 449, in init_library
    handle = ctypes.CDLL(os.path.join(dir_path, libname))
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\I\\AppData\\Local\\Temp\\_MEI70042\\koboldcpp_noavx2.dll'. Most likely this dynlib/dll was not found when the
 application was frozen.
```

**Comment by LostRuins** [comment]
Currently, you can enable it with `--noavx2 --nommap --usecpu`, but in future I think I will add a dedicated flag for it.

**Comment by lavilao** [comment]
thank you
