### ISSUE TITLE
Failed to execute script 'koboldcpp' due to unhandled exception!

### ISSUE THREAD

**Issue by Vl-Kawai** [LostRuins/koboldcpp#42]
Hello!
I am tryed to run koboldcpp.exe with Alpaca ggml-model-q4_1.bin but it "Failed to execute script 'koboldcpp' due to unhandled exception!"
What can I do to solve this?

I have 16 Gb RAM and core i7 3770k if it important.
![изображение](https://user-images.githubusercontent.com/130498858/231257868-5d2706d8-9def-4b61-b889-45b2bf69c414.png)

**Comment by henk717** [comment]
Your CPU does not have AVX2 listed as a supported instruction, have you tried the noavx2 version?

**Comment by prostoman** [comment]
The same. It was not possible to launch any of 10 models. I also tried v1.3_noavx2. The result is one: 
OSError: [WinError -1073741795] Windows Error 0xc000001d
[5388] Failed to execute script 'koboldcpp' due to unhandled exception!

if necessary, I can attach a screenshot for all models and versions

16 Gb RAM and Xeon E5-1620

**Comment by greenvision4** [comment]
I agree I have the same situation processor FX-8300 but
my friend got it working the first time he has a Ryzen 5 3600x processor

**Comment by Kotofay** [comment]
Welcome to KoboldCpp - Version 1.4
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas.dll will be required.
Initializing dynamic library: koboldcpp_blas.dll
Loading model: F:\bin\ChatGPT\koala-13B-4bit-128g.GGML.bin
[Parts: 1, Threads: 7]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from F:\bin\ChatGPT\koala-13B-4bit-128g.GGML.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: f16        = 4
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 11749.65 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 401, in <module>
  File "koboldcpp.py", line 352, in main
  File "koboldcpp.py", line 66, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[2652] Failed to execute script 'koboldcpp' due to unhandled exception!

**Comment by LostRuins** [comment]
also since it seems quite a few people are encountering this issue, might be helpful to list which models you are trying to load, and what format (as displayed in console) they are shown to be in

**Comment by ManOfFlash** [comment]
koboldcpp.exe --noblas D:\Alpaca-33B-ggml-4bit-LoRA-merged_2023-03-31\alpaca-33b-ggml-q4_0-lora-merged\ggml-model-q4_0.bin
Welcome to KoboldCpp - Version 1.4
Initializing dynamic library: koboldcpp.dll
Loading model: D:\Alpaca-33B-ggml-4bit-LoRA-merged_2023-03-31\alpaca-33b-ggml-q4_0-lora-merged\ggml-model-q4_0.bin
[Parts: 1, Threads: 3]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from D:\Alpaca-33B-ggml-4bit-LoRA-merged_2023-03-31\alpaca-33b-ggml-q4_0-lora-merged\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: f16        = 2
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size = 110.30 KB
llama_model_load_internal: mem required  = 21695.46 MB (+ 3124.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 401, in <module>
  File "koboldcpp.py", line 352, in main
  File "koboldcpp.py", line 66, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[8944] Failed to execute script 'koboldcpp' due to unhandled exception!
------------------------
AMD FX8350, Win10.
sha256 hash:
2267ed1dc0bf0d6d300ba292c25083c7fa5395f3726c7c68a49b2be19a64b349  alpaca-33b-ggml-q4_0-lora-merged/ggml-model-q4_0.bin

**Comment by LostRuins** [comment]
1. Does it happen in the previous version?
2. Does it happen in the standard llama.cpp exe?

**Comment by prostoman** [comment]
![llama](https://user-images.githubusercontent.com/11855985/231442456-ccd7d751-9d0e-41e6-a291-e6475c380718.jpg)
![llama2](https://user-images.githubusercontent.com/11855985/231442493-f875d639-0a4c-45a1-a6b9-29d2fcd62f60.jpg)

**Comment by rabidcopy** [comment]
https://github.com/ggerganov/llama.cpp/pull/917 should fix this when it gets merged.

**Comment by Des-75** [comment]
![CropImage](https://user-images.githubusercontent.com/19542693/231503782-24535b4f-bd64-47bc-9bc2-feafb0e63082.jpg)
Intel(R) Xeon(R) CPU E5-2670 v2 / 32 Gb / Win10
SHA256: 9cd4d6c1f5f42d5abf529c51bde3303991fba912ab8ed452adfd7c97a4be77d7 *ggml-model-q4_0.bin (llama-13b-ggml-q4_0)

**Comment by LostRuins** [comment]
Hi everyone, new release is out, can you all try it and see if all these issues are resolved?

https://github.com/LostRuins/koboldcpp/releases/tag/v1.5

**Comment by Des-75** [comment]
No:
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\Users\Des\Downloads\LLaMA-ggml-4bit_2023-03-31\llama-13b-ggml-q4_0\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
  File "koboldcpp.py", line 387, in main
  File "koboldcpp.py", line 81, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[4120] Failed to execute script 'koboldcpp' due to unhandled exception!

**Comment by LostRuins** [comment]
@Des-75 , did you try running it with the -noavx2 flag? I can see you are still loading the avx2 enabled library.

To run it with that flag, open command prompt, navigate to the exe path and run it with the command `--noavx2` 
In future I will probably add it as a GUI option too.

**Comment by LostRuins** [comment]
Looks like you did get it to work then. Anyone else?

**Comment by prostoman** [comment]
![1](https://user-images.githubusercontent.com/11855985/231537727-e0ef9a8f-ef0d-444c-b5f6-3a124a941ae7.jpg)
![2](https://user-images.githubusercontent.com/11855985/231537744-9125a34e-a763-42af-bea2-815cc37f6a01.jpg)
![3](https://user-images.githubusercontent.com/11855985/231537757-653dfbd7-7ada-45f1-9971-38bf163f01c1.jpg)

16 Gb RAM and Xeon E5-1620

**Comment by twirus7** [comment]
16 Gb RAM. Xeon E5-2689 with --noavx2 doesn't work


![image](https://user-images.githubusercontent.com/130598300/231552836-20b13e0b-0b9e-4152-8cf4-542d2436a913.png)

**Comment by ManOfFlash** [comment]
On new bild it become working. --noavx2 on FX-8350.

**Comment by Vl-Kawai** [comment]
> --noavx2

It solved my problem, big thanx!

**Comment by Lordbl4** [comment]
error on xeon x3470
```
F:\koboldcpp>koboldcpp.exe --noavx2 --noblas ggml-model-q4_0.bin
Welcome to KoboldCpp - Version 1.5
Attempting to use non-avx2 compatibility library without OpenBLAS.
Initializing dynamic library: koboldcpp_noavx2.dll
Loading model: F:\koboldcpp\ggml-model-q4_0.bin
[Parts: 1, Threads: 3]

---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 0 | AVX512 = 0 | FMA = 0 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from F:\koboldcpp\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
    main(args)
  File "koboldcpp.py", line 387, in main
    loadok = load_model(modelname,8,maxctx,mdl_nparts,args.threads,(not args.nommap))
  File "koboldcpp.py", line 81, in load_model
    ret = handle.load_model(inputs)
OSError: [WinError -1073741795] Windows Error 0xc000001d
[14696] Failed to execute script 'koboldcpp' due to unhandled exception!
```

**Comment by Zeltorix** [comment]
Error on AMD FX-8150
Windows 10 32Gb RAM
![image](https://user-images.githubusercontent.com/61716339/231577325-f5c0bcef-60b1-43f0-81e9-4a4788d77b95.png)

**Comment by LostRuins** [comment]
Okay looking through the screenshots, I suspect that it's not just AVX2 that some of your devices don't support - there's F16C and SSE instructions that are potentially unsupported too. After trying the official avx .exe from the official repo, I noticed those flags are being excluded when building in compatibility mode. So I will follow suit too in the next release

**Comment by LostRuins** [comment]
Okay, can all those who still encounter issues please try v1.6 with the `--noavx2` flag? 

This one should use a closer configuration to the original llama.cpp so it should have wider support. If it's *still* crashing, then I suspect it is not due to unsupported instructions anymore.

**Comment by twirus7** [comment]
Now it works bro. 16gb RAM Xeon E5-2689 win10  v1.6 with --noavx2

**Comment by Fennekofuckitall** [comment]
How i can use --noavx2 flag? Please, i can't find instruction

**Comment by LostRuins** [comment]
@Fennekofuckitall : 

1. Open command prompt with WinKey+R and type '`cmd`'
2. Drag and drop the exe file into the opened command prompt window. You should see the path to the exe file appear.
3. at the end, add ` --noavx2` after the exe filepath.
4. Run the command.

**Comment by Fennekofuckitall** [comment]
I need drag and drop the koboldcpp?

**Comment by Zeltorix** [comment]
Okay, now it works on FX-8150.
![image](https://user-images.githubusercontent.com/61716339/231795296-2afe8a70-274e-4ed4-b129-47448a46db8c.png)

**Comment by LostRuins** [comment]
@Zeltorix Try running it with `--noblas --noavx2`

**Comment by O1dFox** [comment]
What are the minimum requirements to start?

**Comment by D0Gmatist** [comment]
`***
Welcome to KoboldCpp - Version 1.52.2
For command line arguments, please refer to --help
***
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 1114] Произошел сбой в программе инициализации библиотеки динамической компоновки (DLL)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "koboldcpp.py", line 2386, in <module>
  File "koboldcpp.py", line 2231, in main
  File "koboldcpp.py", line 208, in init_library
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\37525\\AppData\\Local\\Temp\\_MEI163442\\koboldcpp_cublas.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[3808] Failed to execute script 'koboldcpp' due to unhandled exception!`

**Comment by henk717** [comment]
@D0Gmatist What OS do you have and what CPU do you have?

**Comment by glloyd0314** [comment]
```
PS C:\Users\i> koboldcpp.exe
***
Welcome to KoboldCpp - Version 1.53
For command line arguments, please refer to --help
***
Setting process to Higher Priority - Use Caution
High Priority for Windows Set: Priority.NORMAL_PRIORITY_CLASS to Priority.HIGH_PRIORITY_CLASS
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=16, config=None, contextsize=4096, debugmode=0, forceversion=0, foreground=False, gpulayers=100, highpriority=True, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='F:/llm-models-gguf/[70B] swallow-70b.Q3_K_M.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=16, useclblast=None, usecublas=['normal', 'mmq'], usemlock=False)
==========
Loading model: F:\llm-models-gguf\[70B] swallow-70b.Q3_K_M.gguf
[Threads: 16, BlasThreads: 16, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9
llama_model_loader: loaded meta data with 21 key-value pairs and 723 tensors from F:\llm-models-gguf\[70B] swallow-70b.Q3_K_M.ggllm_load_vocab: special tokens definition check successful ( 259/43176 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 43176
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = unknown, may not work (guessed)
llm_load_print_meta: model params     = 69.16 B
llm_load_print_meta: model size       = 31.01 GiB (3.85 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.28 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =  145.21 MiB
llm_load_tensors: VRAM used           = 31612.73 MiB
llm_load_tensors: offloading 80 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 81/81 layers to GPU
.............................................................................................Traceback (most recent call last):
  File "koboldcpp.py", line 2455, in <module>
  File "koboldcpp.py", line 2302, in main
  File "koboldcpp.py", line 301, in load_model
OSError: exception: access violation reading 0x000002D4A0054000
[15876] Failed to execute script 'koboldcpp' due to unhandled exception!
```
The problem still exists for me. It is the first time I met it and above is the full code.
My environment is i9-13900K, 2xRTX4090, 128GB DDR5 4800MHz with Windows 11 23H2 22635.2915.
The model is `swallow-70b.Q3_K_M.gguf`, [Swallow 70B from Huggingface](https://huggingface.co/TheBloke/Swallow-70B-GGUF).
Need to mention that `swallow-70b-instruct.Q3_K_M.gguf`, the instruct model from the same family, [Swallow 70B instruct from Huggingface](https://huggingface.co/TheBloke/Swallow-70B-instruct-GGUF), could be easily loaded without any error.
Below is also the full code if needed.
```
PS C:\Users\i> koboldcpp.exe
***
Welcome to KoboldCpp - Version 1.53
For command line arguments, please refer to --help
***
Setting process to Higher Priority - Use Caution
High Priority for Windows Set: Priority.NORMAL_PRIORITY_CLASS to Priority.HIGH_PRIORITY_CLASS
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=16, config=None, contextsize=4096, debugmode=0, forceversion=0, foreground=False, gpulayers=100, highpriority=True, hordeconfig=None, host='', launch=False, lora=None, model=None, model_param='F:/llm-models-gguf/[70B] swallow-70b-instruct.Q3_K_M.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=16, useclblast=None, usecublas=['normal', 'mmq'], usemlock=False)
==========
Loading model: F:\llm-models-gguf\[70B] swallow-70b-instruct.Q3_K_M.gguf
[Threads: 16, BlasThreads: 16, SmartContext: False, ContextShift: True]

The reported GGUF Arch is: llama

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9
  Device 1: NVIDIA GeForce RTX 4090, compute capability 8.9
llama_model_loader: loaded meta data with 22 key-value pairs and 723 tensors from F:\llm-models-gguf\[70B] swallow-70b-instruct.llm_load_vocab: special tokens definition check successful ( 259/43176 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 43176
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = unknown, may not work
llm_load_print_meta: model params     = 69.16 B
llm_load_print_meta: model size       = 31.01 GiB (3.85 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.28 MiB
llm_load_tensors: using CUDA for GPU acceleration
llm_load_tensors: system memory used  =  145.21 MiB
llm_load_tensors: VRAM used           = 31612.73 MiB
llm_load_tensors: offloading 80 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 81/81 layers to GPU
....................................................................................................
Automatic RoPE Scaling: Using (scale:1.000, base:10000.0).
llama_new_context_with_model: n_ctx      = 4176
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: VRAM kv self = 1305.00 MB
llama_new_context_with_model: KV self size  = 1305.00 MiB, K (f16):  652.50 MiB, V (f16):  652.50 MiB
llama_build_graph: non-view tensors processed: 1684/1684
llama_new_context_with_model: compute buffer total size = 581.35 MiB
llama_new_context_with_model: VRAM scratch buffer: 578.16 MiB
llama_new_context_with_model: total VRAM used: 33495.89 MiB (model: 31612.73 MiB, context: 1883.16 MiB)
Load Model OK: True
Embedded Kobold Lite loaded.
Starting Kobold API on port 5001 at http://localhost:5001/api/
Starting OpenAI Compatible API on port 5001 at http://localhost:5001/v1/
======
Please connect to custom endpoint at http://localhost:5001
```

**Comment by LostRuins** [comment]
If one swallow model works and the other doesn't for the same quant then I would suspect the model file itself has issues. Maybe redownload or requantize it?

**Comment by glloyd0314** [comment]
> If one swallow model works and the other doesn't for the same quant then I would suspect the model file itself has issues. Maybe redownload or requantize it?

It seems to be the problem of the downloaded model. At least I have already another quantized Q3_K_S it works well. I would try to redownload the Q3_K_M ver to see whether the Q3_K_M gguf is really broken or not. Anyway thanks for your help!
