### ISSUE TITLE
ValueError on MacOS. Quantizations changed in GGJTv2. Can only convert unquantized GGML files older than GGJTv2. Sorry, your GGJTv1 file of type MOSTLY_Q5_1 is not eligible for conversion.

### ISSUE THREAD

**Issue by yukiarimo** [LostRuins/koboldcpp#454]
Workflow:

MacBook Pro 14" M1 16 Ram
Python 3.10.12
GNU Make 3.81
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix

The model I tried: https://huggingface.co/TehVenom/Pygmalion-7b-4bit-Q5_1-GGML/tree/main

After running: `convert-llama-ggml-to-gguf.py` in koboldcpp

I get this error:

(ai) yuki@yuki koboldcpp % python convert-llama-ggml-to-gguf.py --input '/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/models/Pygmalion-7b.bin' --output Pygmalion-gguf.bin
* Using config: Namespace(input=PosixPath('/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/models/Pygmalion-7b.bin'), output=PosixPath('Pygmalion-gguf.bin'), name=None, desc=None, gqa=1, eps='5.0e-06', context_length=2048, model_metadata_dir=None, vocab_dir=None, vocabtype='spm')

=== WARNING === Be aware that this conversion script is best-effort. Use a native GGUF model if possible. === WARNING ===

- Note: If converting LLaMA2, specifying "--eps 1e-5" is required. 70B models also need "--gqa 8".
* Scanning GGML input file
* File format: GGJTv1 with ftype MOSTLY_Q5_1
Traceback (most recent call last):
  File "/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/koboldcpp/convert-llama-ggml-to-gguf.py", line 451, in <module>
    main()
  File "/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/koboldcpp/convert-llama-ggml-to-gguf.py", line 428, in main
    offset = model.load(data, 0)
  File "/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/koboldcpp/convert-llama-ggml-to-gguf.py", line 194, in load
    self.validate_conversion(hp.ftype)
  File "/Volumes/Yuki 1/Work/Github/yuna-ai/lib/yunacpp/koboldcpp/convert-llama-ggml-to-gguf.py", line 187, in validate_conversion
    raise ValueError(f'{err} Sorry, your {self.file_format.name}v{self.format_version} file of type {ftype.name} is not eligible for conversion.')
ValueError: Quantizations changed in GGJTv2. Can only convert unquantized GGML files older than GGJTv2. Sorry, your GGJTv1 file of type MOSTLY_Q5_1 is not eligible for conversion.

**Comment by yukiarimo** [comment]
Ok, thanks
