### ISSUE TITLE
Error loading TheBloke/Saily_220b

### ISSUE THREAD

**Issue by frz121** [LostRuins/koboldcpp#570]
Hello!
An error occurs when trying to run the model TheBloke/Saily_220B-GGUF.
I tried the models saily_220b.Q8_0.gguf and saily_220b.Q6_0.gguf with the same error.
Before this, I ran Falcon 190b (Q8) without problems, with CUDA and without.

Welcome to KoboldCpp - Version 1.52.2
For command line arguments, please refer to --help
***
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.dll
==========
Namespace(bantokens=None, blasbatchsize=512, blasthreads=27, config=None, contextsize=1024, debugmode=0, forceversion=0, foreground=False, gpulayers=2, highpriority=False, hordeconfig=None, host='', launch=True, lora=None, model=None, model_param='D:/LLM/saily_220b.Q8_0.gguf', multiuser=1, noavx2=False, noblas=False, nommap=False, noshift=False, onready='', port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], skiplauncher=False, smartcontext=False, tensor_split=None, threads=27, useclblast=None, usecublas=None, usemlock=False)
==========
Loading model: D:\LLM\saily_220b.Q8_0.gguf
[Threads: 27, BlasThreads: 27, SmartContext: False, ContextShift: True]

---
Identified as LLAMA model: (ver 6)
Attempting to Load...
---
Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
llama_model_loader: loaded meta data with 24 key-value pairs and 2190 tensors from D:\LLM\saily_220b.Q8_0.gguf (version GGUF V3 (latest))
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 243
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = ?B
llm_load_print_meta: model ftype      = unknown, may not work (guessed)
llm_load_print_meta: model params     = 208.45 B
llm_load_print_meta: model size       = 206.28 GiB (8.50 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: PAD token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.84 MiB
llm_load_tensors: mem required  = 211228.30 MiB
....................................................................................................
Automatic RoPE Scaling: Using (scale:1.000, base:10000.0).
llama_new_context_with_model: n_ctx      = 1104
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  = 1047.94 MiB, K (f16):  523.97 MiB, V (f16):  523.97 MiB
ggml_new_object: not enough space in the context's memory pool (needed 3342848, available 3342480)
Traceback (most recent call last):
  File "koboldcpp.py", line 2386, in <module>
  File "koboldcpp.py", line 2263, in main
  File "koboldcpp.py", line 302, in load_model
OSError: exception: access violation reading 0x0000000000000000
[15964] Failed to execute script 'koboldcpp' due to unhandled exception!

**Comment by LostRuins** [comment]
Hmm, are you able to load it within llama.cpp? Unfortunately I don't have that much RAM myself so testing it will be impossible for me. Can you also try [v1.51.1](https://github.com/LostRuins/koboldcpp/releases/tag/v1.51.1) and see if it works?

**Comment by LostRuins** [comment]
Hmm okay I'd recommended opening an issue on their github
