### ISSUE TITLE
[User] OSError: [WinError -1073741795] Windows Error 0xc000001d

### ISSUE THREAD

**Issue by Ph0rk0z** [LostRuins/koboldcpp#61]
Windows 10, AMD PhenomII, 16gb of ram. AMD Rx580 GPU

kobold CPP fails like this.

```
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\SD\llamaCPP\models\alpaca-native-7b-ggml\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  59.11 KB
llama_model_load_internal: mem required  = 5809.32 MB (+ 1026.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
  File "koboldcpp.py", line 387, in main
  File "koboldcpp.py", line 81, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[932] Failed to execute script 'koboldcpp' due to unhandled exception!


CLBlast


---
Identified as LLAMA model: (ver 3)
Attempting to Load...
---
System Info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
llama.cpp: loading model from C:\SD\llamaCPP\models\alpaca-native-7b-ggml\ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  59.11 KB
llama_model_load_internal: mem required  = 5809.32 MB (+ 1026.00 MB per state)
Traceback (most recent call last):
  File "koboldcpp.py", line 439, in <module>
  File "koboldcpp.py", line 387, in main
  File "koboldcpp.py", line 81, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[228] Failed to execute script 'koboldcpp' due to unhandled exception!
```

Also tried noavx2 and similar parameters. Normal llama CPP fails silently.

What do? How to even debug this? I might try plain CPP on linux later and see what happens too.

**Comment by LostRuins** [comment]
The error log above shows you are not running in `--noavx2` mode, otherwise it should load the noavx2 library instead. 

Nevertheless, if normal llama.cpp AVX also doesn't work for you then your device may not even support the basic AVX instruction, in which case neither will work.

**Comment by Ph0rk0z** [comment]
Ahh ok. So AVX is required.

**Comment by LostRuins** [comment]
It may be possible to do a manual noavx build from source, but that is not supported. You can try compiling it from source with `-march=native`.

**Comment by Ph0rk0z** [comment]
What can I use to build on windows?

**Comment by LostRuins** [comment]
Win64devkit might work

**Comment by Ph0rk0z** [comment]
I was able to finally compile with msys and mingw. It runs and generates tokens at like 2-300ms/token. clblas works with the GPU so the prompt is constructed faster than the generation.


[dist.zip](https://github.com/LostRuins/koboldcpp/files/11243166/dist.zip)
