### ISSUE TITLE
Prompt processing extremely slow and intensive on my hardware with later revisions

### ISSUE THREAD

**Issue by Drael64** [LostRuins/koboldcpp#619]
I tried the latest version recently - unusual hardware FYI, AMD Radeon 6600M (8gb vram, 32gb ram system on windows 11). The prompt processing was extraordinarily slow and brought my entire computer to a crawl for a mere 10.7B language model at a modest q3_km quant. Reverted to 15.1 and all is well again (smooth prompt processing speed and no computer slow downs)

**Comment by Skydea777** [comment]
Same problem here, from 1.55 onwards the performance is abysmall.
From, lets say 2 - 4 Tokens a second as an example:
![WindowsTerminal_c2v7XUchSc](https://github.com/LostRuins/koboldcpp/assets/156956074/54083a21-d793-4784-9488-2e29394375b1)
 on a hefty model I now only have 0,03 Tokens a second (generating the text itself, cublas processing is mostly fine)! 
 (GPU RTX 3080 Ampere Generation -> compute capability 8.6, 64GB RAM, AMD Ryzen 7 5800X 8-Core Processor @ 4,7Ghz)
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/d2dc56d7-2e11-40ae-8b4c-53d5dc8faffe)

The error seems to come from llama.cpp / its python interface itself.
As example, if I load it directly via llama.cpp or oobabooga webui that is also using llama.cpp (Version 2.2.26) it is plagued with the same error.

I do not want to admit how much time I wasted (20+ hours) searching for the problem here on my side, but as I can reproduce the problem again and again by using Version 1.54 of Kobold.cpp that seems to use an older version of LLama.cpp in that moment, it must be the cause.

But I have no way to somehow... change it.
I played with all possible settings and models, the bug is a constant, unchanging.

**Comment by Drael64** [comment]
> ug is a constan

It's troublesome. My machine just DIES when I run the newer versions. Particularly troublesome because the new imatrix quants aren't supported by kobold yet, so if this isn't fixed before they come out, I basically wont be able to use them. If it came from llama.cpp wouldn't it also effect the older versions of kobold.cpp? Because simply reverting kobold version fixed it for me. I guess it could be some interaction....

**Comment by Skydea777** [comment]
Sorry if I was unclear, the compiled version of KoboldCpp (1.54 and below) isn't affected by a newer llama.cpp, just wanted to explain that the newer Versions of KoboldCpp, LLama.cpp and abetlen/llama-cpp-python

**Comment by Tacx79** [comment]
I noticed that too in past days

Mixtral 8x7b instruct q8, CuBLAS + 0 layers on gpu, Koboldcpp 1.55.1
Ryzen 1700, gtx 1080, 80gb ram ddr4, I think the blas processing was in ranges under 30-50ms/t when using other models, not sure about mixtral on previous versions, I also think that generation speed went down too (yi-34b q8 have around 900-1100ms/t on previous versions).
```
Processing Prompt [BLAS] (57 / 57 tokens)
Generating (191 / 1024 tokens)
(EOS token triggered!)
ContextLimit: 9547/32768, Processing:71.01s (1245.8ms/T), Generation:163.57s (856.4ms/T), Total:234.59s (0.81T/s)
```

I can do more tests with fixed context and different versions if required

**Comment by Skydea777** [comment]
Just to mention it here as I made some more data:


Yeah same Issue I also posted here: "https://github.com/LostRuins/koboldcpp/issues/619" and I am losing my mind with this Problem!

Interesstingly it does not happens when I compile my own Cuda Version of LLamaCpp (Using the latest build from master and Cuda Toolkit 12.2.2 and Visual Studio 2019 Community Edition) with CMake. 
the build was executet via:
"cmake .. -DLLAMA_CUBLAS=ON"
"cmake --build . --config Release"
(I reinstalled VS 2019 Community Edition and Cuda Toolkit. In that order and set all needed Enviroment Variables.)
Everything works wonderful with identical settings used in KoboldCPP while using the "Main.exe" This test withoug GPU Layers:
.\main.exe -i --color -m "C:\AI\CPP\Models-CPP\Noromaid-13B-0.4-DPO.q5_k_m.gguf" -r "Tell me about yourself."
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/503a49e2-0ba2-46ef-8ae0-8ace31bc02d7)
Also with GPU Layers (this above was just a test for my sanity):
.\main.exe -i --color -m "C:\AI\CPP\Models-CPP\Noromaid-13B-0.4-DPO.q5_k_m.gguf" -ngl 26 -r "Tell me about yourself."
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/7a8fea4f-f47c-4aba-9ae3-d5ec290db89b)

Using the "server.exe" in combination with Sillytaven (Regardles of Settings in there) works pretty well.
.\server -v -t 8 -tb 8 -c 8192 -b 512 -ngl 26 -m "C:\AI\CPP\Models-CPP\Noromaid-13B-0.4-DPO.q5_k_m.gguf"
Speed is not really impaired even if it is hallucinating heavily... for what ever reason.


Using the Prebuild Version von LLama.cpp Version b1961
I get pretty much the exact same results:
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/73cd3f85-e90d-49b2-856e-a4882a2b62a3)

Also Server.exe still halluciating like crazy.. i mean .. rolling my chair back then squeezing my ankle  and after that saying... gibberish with %COSTCO ... interessting.
But it seems to work.


KoboldCpp 1.54:
Settings
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/7719bee5-c803-48ee-9757-e6397aef7b16)

Result:
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/cdf66d2d-a0ad-4b12-8406-2b1539616e63)


KoboldCpp 1.55.1:
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/b45ffd79-59c0-47e0-a331-053754223c02)


Result:
![grafik](https://github.com/LostRuins/koboldcpp/assets/156956074/239646e9-5ab9-4fc5-b435-b570d05ad894)



As you can see, the Bug is really only happening in 1.55+ of Kobold Cpp, it is completly irrelevant how much Layers I choose to use, if I use LowVram or not, it ... just stopped working and I am out of ideas, no seriously, I am searching for days why this is not working! 

Please Help! :(

**Comment by LostRuins** [comment]
Hi, can you try 1.56? The backends were reworked. See if that provides any improvement.

**Comment by Tacx79** [comment]
gtx 1080 - 0 layers on gpu
ryzen 1700 - 8 cpu threads

1.54 looks a bit slower than usual but it might be just long uptime issue with windows

1.54 - cublas - mixtral instruct q8:
``` 
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (116 / 1024 tokens)
ContextLimit: 4811/32768, Processing:186.04s (39.6ms/T), Generation:55.66s (479.8ms/T)
```

1.54 - cublas - yi-34b-chat q8:
```
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (147 / 1024 tokens)
ContextLimit: 4794/32768, Processing:182.92s (39.4ms/T), Generation:189.22s (1287.2ms/T)
```

1.56 - cublas - mixtral instruct q8:
```
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (94 / 1024 tokens)
ContextLimit: 4789/32768, Processing:260.87s (55.6ms/T), Generation:56.31s (599.1ms/T)
```

1.56 - cublas - yi-34b-chat q8:
```
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (154 / 1024 tokens)
ContextLimit: 4801/32768, Processing:214.81s (46.2ms/T), Generation:230.69s (1498.0ms/T)
```

1.56 - vulkan - after loading ~80% of both models:
(same config file, only switched cublas to vulcan)
```
Traceback (most recent call last):
File "koboldcpp.py", line 2580, in <module>
File "koboldcpp.py", line 2426, in main
File "koboldcpp.py", line 328, in load_model
OSError: exception: access violation reading 0x000000A24C5F0000
[29244] Failed to execute script 'koboldcpp' due to unhandled exception!
```

**Comment by LostRuins** [comment]
@Tacx79 so for you 1.54 is the last good speed? what about between 1.55.1 and 1.56? Same speeds?

**Comment by Tacx79** [comment]
1.53 and 1.54 have similar good speeds, 1.55.1 slows down a lot, 1.56 is faster than 1.55.1 but still slower than 1.54 and 1.53

```
1.53 - cublas - mixtral instruct q8
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (131 / 1024 tokens)
ContextLimit: 4826/32768, Processing:180.39s (38.4ms/T), Generation:61.69s (470.9ms/T)
```
```
1.53 - cublas - yi-34b-chat q8
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (121 / 1024 tokens)
ContextLimit: 4768/32768, Processing:177.63s (38.2ms/T), Generation:151.76s (1254.3ms/T)
```
```
1.54 - cublas - mixtral instruct q8
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (74 / 1024 tokens)
ContextLimit: 4769/32768, Processing:178.48s (38.0ms/T), Generation:35.93s (485.5ms/T)
```
```
1.54 - cublas - yi-34b-chat q8
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (166 / 1024 tokens)
ContextLimit: 4813/32768, Processing:179.51s (38.6ms/T), Generation:213.89s (1288.5ms/T)
```
```
1.55.1 - cublas - mixtral instruct q8
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (172 / 1024 tokens)
ContextLimit: 4867/32768, Processing:559.54s (119.2ms/T), Generation:115.84s (673.5ms/T)
```
```
1.55.1 - cublas - yi-34b-chat q8
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (142 / 1024 tokens)
ContextLimit: 4789/32768, Processing:198.12s (42.6ms/T), Generation:240.98s (1697.0ms/T)
```
```
1.56 - cublas - mixtral instruct q8
Processing Prompt [BLAS] (4695 / 4695 tokens)
Generating (93 / 1024 tokens)
ContextLimit: 4788/32768, Processing:209.27s (44.6ms/T), Generation:58.71s (631.2ms/T)
```
```
1.56 - cublas - yi-34b-chat q8
Processing Prompt [BLAS] (4647 / 4647 tokens)
Generating (168 / 1024 tokens)
ContextLimit: 4815/32768, Processing:194.13s (41.8ms/T), Generation:264.54s (1574.7ms/T)
```

**Comment by Skydea777** [comment]
> Hi, can you try 1.56? The backends were reworked. See if that provides any improvement.

I am deeply Sorry had multiple things hit the fan (work related) and did not manage to tell the findings I came across!
--> **It was the threads count!** <--

8 Core CPU with 16 "Threads"
Just if you ever use all threads everything grinds to a halt as shown in my Screenshots, in Llama.cpp I only used the "real" cores so I had good performance.

If it is possible add a notice (Question Mark with additional Informations if you hover above it like in SillyTavern) that if you use all avaiable threads it might lead to massivly degraded performance.

Again I am sorry for not Updating, I searched for this error for over ~30 hours, so you can guess my frustration and the shame that washed over me as I noticed what did happen.

Thank You for your hard work @LostRuins !

**Comment by Skydea777** [comment]
Okay an here are my Benchmarks with my Character Card Torture 2000, the used Model is this time "_Noromaid-v0.4-Mixtral-Instruct-8x7b.q5_k_m.kcpps_":


### 1.54

> Processing Prompt [BLAS] (1292 / 1292 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1355/16384, Processing:47.38s (36.7ms/T)
> Generation:18.84s (303.9ms/T), Total:66.23s (0.94T/s)

**0.94T/s**


### 1.55:
> Processing Prompt [BLAS] (1292 / 1292 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1399/16384, Processing:34.86s (27.0ms/T)
> Generation:29.58s (279.1ms/T), Total:64.44s (1.64T/s)

**1.64T/s**


### 1.55.1:
> Processing Prompt [BLAS] (1292 / 1292 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1380/16384, Processing:33.46s (25.9ms/T)
> Generation:25.20s (289.6ms/T), Total:58.66s (1.48T/s)

**1.48T/s**


### 1.56 [CuBlas]:
> Processing Prompt [BLAS] (1292 / 1292 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1387/16384, Processing:28.86s (22.3ms/T)
> Generation:27.42s (291.7ms/T), Total:56.28s (598.8ms/T = 1.67T/s)

**1.67T/s**


### 1.56 [Vulcan]:
> ERROR

> Loading model: C:\AI\CPP\Models-CPP\Noromaid-v0.4-Mixtral-Instruct-8x7b.q5_k_m.gguf

> [Threads: 8, BlasThreads: 8, SmartContext: False, ContextShift: True]

> The reported GGUF Arch is: llama

> ---
> Identified as GGUF model: (ver 6)
> Attempting to Load...
> ---
> Using automatic RoPE scaling. If the model has customized RoPE settings, they will be used directly instead!
> System Info: AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | > ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 |
> ggml_vulkan: Using NVIDIA GeForce RTX 3080
> ggml_vulkan: 16-bit enabled
> llama_model_loader: loaded meta data with 26 key-value pairs and 995 tensors from C:\AI\CPP\Models-CPP\Noromaid-v0.4-Mixtral-Instruct-8x7b.q5_k_m.gguf (version GGUF V3 (latest))
> llm_load_vocab: special tokens definition check successful ( 259/32000 ).
> llm_load_print_meta: format           = GGUF V3 (latest)
> llm_load_print_meta: arch             = llama
> llm_load_print_meta: vocab type       = SPM
> llm_load_print_meta: n_vocab          = 32000
> llm_load_print_meta: n_merges         = 0
> llm_load_print_meta: n_ctx_train      = 32768
> llm_load_print_meta: n_embd           = 4096
> llm_load_print_meta: n_head           = 32
> llm_load_print_meta: n_head_kv        = 8
> llm_load_print_meta: n_layer          = 32
> llm_load_print_meta: n_rot            = 128
> llm_load_print_meta: n_embd_head_k    = 128
> llm_load_print_meta: n_embd_head_v    = 128
> llm_load_print_meta: n_gqa            = 4
> llm_load_print_meta: n_embd_k_gqa     = 1024
> llm_load_print_meta: n_embd_v_gqa     = 1024
> llm_load_print_meta: f_norm_eps       = 0.0e+00
> llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
> llm_load_print_meta: f_clamp_kqv      = 0.0e+00
> llm_load_print_meta: f_max_alibi_bias = 0.0e+00
> llm_load_print_meta: n_ff             = 14336
> llm_load_print_meta: n_expert         = 8
> llm_load_print_meta: n_expert_used    = 2
> llm_load_print_meta: rope scaling     = linear
> llm_load_print_meta: freq_base_train  = 1000000.0
> llm_load_print_meta: freq_scale_train = 1
> llm_load_print_meta: n_yarn_orig_ctx  = 32768
> llm_load_print_meta: rope_finetuned   = unknown
> llm_load_print_meta: model type       = 7B
> llm_load_print_meta: model ftype      = unknown, may not work
> llm_load_print_meta: model params     = 46.70 B
> llm_load_print_meta: model size       = 30.02 GiB (5.52 BPW)
> llm_load_print_meta: general.name     = .
> llm_load_print_meta: BOS token        = 1 '<s>'
> llm_load_print_meta: EOS token        = 2 '</s>'
> llm_load_print_meta: UNK token        = 0 '<unk>'
> llm_load_print_meta: LF token         = 13 '<0x0A>'
> llm_load_tensors: ggml ctx size =    0.76 MiB
> llm_load_tensors: offloading 6 repeating layers to GPU
> llm_load_tensors: offloaded 6/33 layers to GPU
> llm_load_tensors:        CPU buffer size = 30735.49 MiB
> llm_load_tensors:     Vulkan buffer size =  5727.56 MiB
> ....................................................................................................
> Automatic RoPE Scaling: Using model internal value.
> llama_new_context_with_model: n_ctx      = 16464
> llama_new_context_with_model: freq_base  = 1000000.0
> llama_new_context_with_model: freq_scale = 1
> llama_kv_cache_init: Vulkan_Host KV buffer size =  1672.12 MiB
> llama_kv_cache_init:     Vulkan KV buffer size =   385.88 MiB
> llama_new_context_with_model: KV self size  = 2058.00 MiB, K (f16): 1029.00 MiB, V (f16): 1029.00 MiB
> llama_new_context_with_model: Vulkan_Host input buffer size   =    40.22 MiB
> llama_new_context_with_model:     Vulkan compute buffer size =  1233.28 MiB
> llama_new_context_with_model: Vulkan_Host compute buffer size =  1189.13 MiB
> llama_new_context_with_model: graph splits (measure): 5
> GGML_ASSERT: ggml-vulkan.cpp:2738: src1 == nullptr || ggml_vk_dim01_contiguous(src1)
> 
> [Verarbeitung des Prozesses mit Code 3 (0x00000003) beendet]

**ERROR**

**Comment by Tacx79** [comment]
> I am deeply Sorry had multiple things hit the fan (work related) and did not manage to tell the findings I came across! --> **It was the threads count!** <--
> 
> 8 Core CPU with 16 "Threads" Just if you ever use all threads everything grinds to a halt as shown in my Screenshots, in Llama.cpp I only used the "real" cores so I had good performance.

That would be the repeat of #446

**Comment by LostRuins** [comment]
@Skydea777 that's expected - Mixtral is not yet supported on Vulkan. I'll add a note to the release page

**Comment by Skydea777** [comment]
@LostRuins 
Ah good to know!
Here is one more test with "Noromaid-13b-v0.3-T4.q5_k_m.gguf" only change is the increase of Layers from 6 to 22 for the 13B model.
Settings File:
[CPP-Settings-V104-Noromaid-13b-v0.3-T4.q5_k_m.kcpps.zip](https://github.com/LostRuins/koboldcpp/files/14075435/CPP-Settings-V104-Noromaid-13b-v0.3-T4.q5_k_m.kcpps.zip)


### 1.54

> Processing Prompt [BLAS] (1329 / 1329 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1389/16384, Processing:10.77s (8.1ms/T), Generation:14.15s (239.8ms/T)
> Total:24.92s (2.37T/s)

**2.37/s**



### 1.55

> Processing Prompt [BLAS] (1329 / 1329 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1409/16384, Processing:10.41s (7.8ms/T), Generation:19.43s (245.9ms/T)
> Total:29.84s (2.65T/s)

**2.65/s**



### 1.55.1

> Processing Prompt [BLAS] (1329 / 1329 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1404/16384, Processing:9.23s (6.9ms/T), Generation:17.77s (240.1ms/T)
> Total:27.00s (2.74T/s)

**2.74/s**



### 1.56 (CuBlas)

> Processing Prompt [BLAS] (1329 / 1329 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1409/16384, Processing:7.30s (5.5ms/T), Generation:19.66s (248.9ms/T)
> Total:26.96s (341.3ms/T = 2.93T/s)

**2.93/s**



### 1.56 (Vulkan) -> Crashed THREE TIMES while loading the Model.

> Processing Prompt [BLAS] (1329 / 1329 tokens)
> Generating (1025 / 1024 tokens)
> ContextLimit: 1424/16384, Processing:7.27s (5.5ms/T), Generation:23.36s (248.6ms/T)
> Total:30.63s (325.9ms/T = 3.07T/s)

**3.07/s**
Way better than expected! Nice!

**Comment by Drael64** [comment]
I believe I've been using 1.52, but that sounds about right on the versions that work well. Also tried the latest version - same issue.  The difference for me is so large than I've never waited for a mere 1000 token prompt to even finish - it basically hangs my entire machine (like literally freezes and the prompt processing takes at least more than 8-10 minutes!). GPU is AMD 6600M, and it normally chugs along just fine with smaller models finishing the prompt and reply in a minute or so.  So it's like a more than 10x slowdown for me. Seems like other users aren't hit as hard with better gpus.  

Using CLBlast, can't say I've tried vulkan. Using all very typical recommended type settings. I probably should, given that vulkan has special support qualities for AMD drivers. But for now, the older version works fine.

**Comment by henk717** [comment]
Definately try Vulkan, its way faster than CLBlast.
