### ISSUE TITLE
Error when using  OpenAI Compatible API

### ISSUE THREAD

**Issue by foxbg** [LostRuins/koboldcpp#643]
I'm getting

`'NoneType' object has no attribute 'encode'`

KoboldCpp - Version 1.56

When using "ggerganov/llama.cpp" There is no error.

**Comment by LostRuins** [comment]
What frontend are you using?

**Comment by foxbg** [comment]
chatdev is consuming via API. Here is the error in chatdev
```
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "C:\dev\python\ChatDev\camel\utils.py", line 154, in wrapper
    return func(self, *args, **kwargs)
  File "C:\dev\python\ChatDev\camel\agents\chat_agent.py", line 239, in step
    response = self.model_backend.run(messages=openai_messages)
  File "C:\dev\python\ChatDev\camel\model_backend.py", line 105, in run
    num_prompt_tokens=response.usage.prompt_tokens,
AttributeError: 'NoneType' object has no attribute 'usage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\dev\python\ChatDev\run.py", line 134, in <module>
    chat_chain.execute_chain()
  File "C:\dev\python\ChatDev\chatdev\chat_chain.py", line 168, in execute_chain
    self.execute_step(phase_item)
  File "C:\dev\python\ChatDev\chatdev\chat_chain.py", line 138, in execute_step
    self.chat_env = self.phases[phase].execute(self.chat_env,
  File "C:\dev\python\ChatDev\chatdev\phase.py", line 295, in execute
    self.chatting(chat_env=chat_env,
  File "C:\dev\python\ChatDev\chatdev\utils.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "C:\dev\python\ChatDev\chatdev\phase.py", line 133, in chatting
    assistant_response, user_response = role_play_session.step(input_user_msg, chat_turn_limit == 1)
  File "C:\dev\python\ChatDev\camel\agents\role_playing.py", line 247, in step
    assistant_response = self.assistant_agent.step(user_msg_rst)
  File "C:\Users\user\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\user\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\user\.conda\envs\chatdev\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1fdfd864340 state=finished raised AttributeError>]
```

**Comment by foxbg** [comment]
I've modified the code to print response
Added
`print("<DEBUG>",response)`
When using kobold.cpp I'm getting 
`<DEBUG> None`
When using [llama.cpp](https://github.com/ggerganov/llama.cpp) I'm getting
`<DEBUG> ChatCompletion(id='chatcmpl-7pxF40MlfUg8MHpAX7JHtCLlxu7S9RwY', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content='<INFO> Website </INFO>', role='assistant', function_call=None, tool_calls=None))], created=1706558828, model='gpt-3.5-turbo-16k', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=8, prompt_tokens=655, total_tokens=663))`

**Comment by foxbg** [comment]
I've changed the port to 8080
Here is a capture of the traffic. It seems it uses correct URL. Stripped non relevant data.
```
POST /v1/chat/completions HTTP/1.1
Host: 127.0.0.1:8080
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: application/json
Content-Type: application/json
User-Agent: OpenAI/Python 1.3.3
X-Stainless-Lang: python
X-Stainless-Package-Version: 1.3.3
X-Stainless-OS: Windows
X-Stainless-Arch: other:amd64
X-Stainless-Runtime: CPython
X-Stainless-Runtime-Version: 3.9.18
Authorization: Bearer your_OpenAI_API_key
Content-Length: 2947

{"messages": [{"role": "system", "content": "ChatDev is a software company powered by multiple intelligent agents, such as chief executive officer, chief human resources officer, chief product officer, chief technology officer, etc, with a multi-agent organizational structure and the mission of 'changing the digital world through programming'.\n......"}, {"role": "user", "content": "ChatDev ..."}], "model": "gpt-3.5-turbo-16k", "frequency_penalty": 0.0, "logit_bias": {}, "max_tokens": 15821, "n": 1, "presence_penalty": 0.0, "stop": null, "stream": false, "temperature": 0.2, "top_p": 1.0, "user": ""}HTTP/1.0 200 OK
Server: ConcedoLlamaForKoboldServer 
Date: Tue, 30 Jan 2024 17:17:51 GMT
content-length: 4
access-control-allow-origin: *
access-control-allow-methods: *
access-control-allow-headers: *, Accept, Content-Type, Content-Length, Cache-Control, Accept-Encoding, X-CSRF-Token, Client-Agent, X-Fields, Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override, apikey, genkey
cache-control: no-store
content-type: application/json

null
```

And as comparaison the upstream llama.ccp
```
POST /v1/chat/completions HTTP/1.1
Host: 127.0.0.1:8080
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: application/json
Content-Type: application/json
User-Agent: OpenAI/Python 1.3.3
X-Stainless-Lang: python
X-Stainless-Package-Version: 1.3.3
X-Stainless-OS: Windows
X-Stainless-Arch: other:amd64
X-Stainless-Runtime: CPython
X-Stainless-Runtime-Version: 3.9.18
Authorization: Bearer your_OpenAI_API_key
Content-Length: 2947

{"messages": [{"role": "system", "content": "ChatDev ...}HTTP/1.1 200 OK
Access-Control-Allow-Origin: 
Content-Length: 310
Content-Type: application/json; charset=utf-8
Keep-Alive: timeout=5, max=5
Server: llama.cpp

{"choices":[{"finish_reason":"stop","index":0,"message":{"content":"<INFO> Website </INFO>","role":"assistant"}}],"created":1706635645,"id":"chatcmpl-KVOgQkKARhMKOU83W8k2AsLkCKnKrxxz","model":"gpt-3.5-turbo-16k","object":"chat.completion","usage":{"completion_tokens":8,"prompt_tokens":655,"total_tokens":663}}
```

**Comment by LostRuins** [comment]
Thanks, and what does it show inside the koboldcpp terminal? Do you see your inputs and the generated tokens shown in the console?

**Comment by foxbg** [comment]
I do see the input and then the error
```
Please connect to custom endpoint at http://localhost:8080

Input: {"messages": [{"role": "system", "content": "ChatDev is a software company powered by multiple intelligent agents,...."}], "model": "gpt-3.5-turbo-16k", "frequency_penalty": 0.0, "logit_bias": {}, "max_tokens": 15821, "n": 1, "presence_penalty": 0.0, "stop": null, "stream": false, "temperature": 0.2, "top_p": 1.0, "user": ""}
'NoneType' object has no attribute 'encode'
```

**Comment by LostRuins** [comment]
Okay I have found the issue and fixed it.

However, I also noticed some issues with your inputs:

1. `stop` should either be excluded, set to `[]` or utilized. Setting it to `null` caused errors.
2. `max_tokens` of 15821 is too much. You should reduce it to half or less of your max context length (try 1000).

**Comment by foxbg** [comment]
Great. I'll report this to the chatdev github.

**Comment by LostRuins** [comment]
Should be fixed now in v1.57!

**Comment by foxbg** [comment]
Confirmed.
