### ISSUE TITLE
[WinError 1114] A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by jm18499** [LostRuins/koboldcpp#785]
D:\AI>koboldcpp.exe --threads 2 --blasthreads 2 --nommap --usecublas --gpulayers 50 --highpriority --blasbatchsize 512 --contextsize 8192

Welcome to KoboldCpp - Version 1.62.2
For command line arguments, please refer to --help

Setting process to Higher Priority - Use Caution
High Priority for Windows Set: Priority.NORMAL_PRIORITY_CLASS to Priority.HIGH_PRIORITY_CLASS
Attempting to use CuBLAS library for faster prompt ingestion. A compatible CuBLAS will be required.
Initializing dynamic library: koboldcpp_cublas.dll
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 373, in __init__
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "koboldcpp.py", line 3195, in <module>
  File "koboldcpp.py", line 2878, in main
  File "koboldcpp.py", line 270, in init_library
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Temp\\_MEI127722\\koboldcpp_cublas.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[14344] Failed to execute script 'koboldcpp' due to unhandled exception!
***

I read through issue #778 and used the DependencyGUI tool and found these two are missing .dlls:
oobe-query-11-1-0.dll
ext-ms-win-core-winrt-remote-11-1-0.dll

I don't know where to download them or what they are exactly.

**Comment by LostRuins** [comment]
Kindly share your System specs and OS version.

Also are you sure those dlls are required? That seems quite unlikely.

**Comment by MEuterpe** [comment]
I got the exactly same error, and the same missing dlls, have you fixed this problem?

**Comment by LostRuins** [comment]
I need to know some system info before I'm able to figure out where the missing dlls are from.

**Comment by MEuterpe** [comment]
> I need to know some system info before I'm able to figure out where the missing dlls are from.

win10 professional with version 22H2, X64 operating system

**Comment by MEuterpe** [comment]
Maybe those two dlls are not the cause of the problem, they are not directly displayed if I don't click on all branches in Dependencies to view. ![1](https://github.com/LostRuins/koboldcpp/assets/167212742/c19315af-d215-45ad-900a-c2c188be585e)I also found other similar missing dlls that were hidden, such as ext-ms-win-com-suspendresiliency-l1-1-0.dll, etc., but they didn't seem important.
![2](https://github.com/LostRuins/koboldcpp/assets/167212742/a2a77739-e301-4ba3-aeeb-a9267961c903)
In addition, if I use the nocuda version and load a model, it will crash after displaying the following information.
***
Welcome to KoboldCpp - Version 1.63
For command line arguments, please refer to --help
* * *
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcp_openblas.d11
/Namespace (bantokens=None, benchmark=None, blasbatchsize=512, blasthreads=13, chatcompletionsadapter=None, config=None. ontextsize=2048, debugmode=0, forceversion=0, foreground=False, gpulayers=200, highpriority=false, hordeconfig=None, host="",ignoremissing=False, Launch=True, lora=None, mmproj=None, model=None, model_param='D: /11ama3 model/Llama3-8B-Chinese-Chat.06_K-gguf', multiuser=1, noav×2=False, noblas=False, nocertify=False, nommap=False, noshift=False, onready="', p assword=None, port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0].sdconfig=None, skiplauncher=False, smartcontext=False, ss1=None, tensor_split=None, threads=13, useciblast=None, usecublas=None, usemlock=False, usevulkan=None)
==========
Loading model: D: \11ama3_model\L1ama3-8B-Chinese-Chat .06_K-gguf
[Threads: 13, BlasThreads: 13, SmartContext: False, ContextShift: True]

**Comment by MEuterpe** [comment]
Enabling the AVX2 can solve the issue.
