### ISSUE TITLE
Cannot load a saved config in 1.63 sometimes

### ISSUE THREAD

**Issue by aleksusklim** [LostRuins/koboldcpp#806]
The KCPPS config:
```js
{"model": null, "model_param": "Lexi-Llama-3-8B-Uncensored-Q5_K_M.gguf", "port": 5001, "port_param": 5001, "host": "", "launch": true, "config": null, "threads": 8, "usecublas": ["normal", "0", "mmq"], "usevulkan": null, "useclblast": null, "noblas": false, "gpulayers": 0, "tensor_split": null, "contextsize": 4096, "ropeconfig": [0.0, 10000.0], "blasbatchsize": 512, "blasthreads": null, "lora": null, "smartcontext": false, "noshift": true, "bantokens": null, "forceversion": 0, "nommap": false, "usemlock": true, "noavx2": false, "debugmode": 0, "skiplauncher": false, "hordeconfig": null, "onready": "", "benchmark": null, "multiuser": 1, "remotetunnel": false, "highpriority": false, "foreground": false, "preloadstory": null, "quiet": false, "ssl": null, "nocertify": false, "sdconfig": null, "mmproj": null, "password": null, "ignoremissing": false, "chatcompletionsadapter": null}
```

I open this config:
![image](https://github.com/LostRuins/koboldcpp/assets/13969463/c6f1b637-20f3-4140-930b-dba07fec1ab6)

I change `Use CuBLAS` to `Use OpenBLAS`:
![image](https://github.com/LostRuins/koboldcpp/assets/13969463/43e55e40-4a35-4bf8-bedc-a3b8da4317d6)

I save the config:
```js
{"model": null, "model_param": "Lexi-Llama-3-8B-Uncensored-Q5_K_M.gguf", "port": 5001, "port_param": 5001, "host": "", "launch": true, "config": null, "threads": 8, "usecublas": null, "usevulkan": null, "useclblast": null, "noblas": false, "gpulayers": 0, "tensor_split": null, "contextsize": 4096, "ropeconfig": [0.0, 10000.0], "blasbatchsize": 512, "blasthreads": null, "lora": null, "smartcontext": false, "noshift": true, "bantokens": null, "forceversion": 0, "nommap": false, "usemlock": true, "noavx2": false, "debugmode": 0, "skiplauncher": false, "hordeconfig": null, "onready": "", "benchmark": null, "multiuser": 1, "remotetunnel": false, "highpriority": false, "foreground": false, "preloadstory": null, "quiet": false, "ssl": null, "nocertify": false, "sdconfig": null, "mmproj": null, "password": null, "ignoremissing": false, "chatcompletionsadapter": null}
```

I restart and load the config:
![image](https://github.com/LostRuins/koboldcpp/assets/13969463/a792eca0-e3f7-4778-bfbb-5dc4c3c9b6c5)

```
***
Welcome to KoboldCpp - Version 1.63
For command line arguments, please refer to --help
***
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "koboldcpp.py", line 2348, in load_config
  File "koboldcpp.py", line 2234, in import_vars
TypeError: argument of type 'NoneType' is not iterable
```

The error prevents loading of all fields, and not just the one it considers broken!

Can you:
1. Fix whatever caused the error here; and
2. Make loading more tolerant to incomplete/bad configs? (As long as it is valid JSON)

**Comment by LostRuins** [comment]
Alright found the issue, I'll fix it. Generally the kcpps file should be fault tolerant, this is one edge case that was missed.

**Comment by LostRuins** [comment]
Hi, Should be fixed in the latest version

**Comment by aleksusklim** [comment]
Yup, it's working!
