### ISSUE TITLE
Windows Error 0xc000001d

### ISSUE THREAD

**Issue by mercurial-moon** [LostRuins/koboldcpp#816]
Logs as under

```
Welcome to KoboldCpp - Version 1.63
For command line arguments, please refer to --help
***
Attempting to use OpenBLAS library for faster prompt ingestion. A compatible libopenblas will be required.
Initializing dynamic library: koboldcpp_openblas.dll
==========
Namespace(bantokens=None, benchmark=None, blasbatchsize=512, blasthreads=3, chatcompletionsadapter=None, config=None, contextsize=2048, debugmode=0, forceversion=0, foreground=False, gpulayers=0, highpriority=False, hordeconfig=None, host='', ignoremissing=False, launch=True, lora=None, mmproj=None, model=None, model_param='C:/Users/Smite/.cache/lm-studio/models/TheBloke/huggingface/mistral-7b-instruct-v0.2.Q4_K_M.gguf', multiuser=1, noavx2=False, noblas=False, nocertify=False, nommap=False, noshift=False, onready='', password=None, port=5001, port_param=5001, preloadstory=None, quiet=False, remotetunnel=False, ropeconfig=[0.0, 10000.0], sdconfig=None, skiplauncher=False, smartcontext=False, ssl=None, tensor_split=None, threads=3, useclblast=None, usecublas=None, usemlock=False, usevulkan=None)
==========
Loading model: C:\Users\Smite\.cache\lm-studio\models\TheBloke\huggingface\mistral-7b-instruct-v0.2.Q4_K_M.gguf
[Threads: 3, BlasThreads: 3, SmartContext: False, ContextShift: True]
Traceback (most recent call last):
  File "koboldcpp.py", line 3220, in <module>
  File "koboldcpp.py", line 2970, in main
  File "koboldcpp.py", line 398, in load_model
OSError: [WinError -1073741795] Windows Error 0xc000001d
[7008] Failed to execute script 'koboldcpp' due to unhandled exception!


```

**Comment by LostRuins** [comment]
Try select the noavx2 option

**Comment by mercurial-moon** [comment]
That worked!! Thanks!

**Comment by LostRuins** [comment]
You can also try the NoAvx2 CLBlast version if you have a GPU.

**Comment by mercurial-moon** [comment]
Thanks! Really appreciate the effort put into KoboldCpp.
