### ISSUE TITLE
OSError: dlopen failed: library "/data/data/com.termux/files/home/koboldcpp/koboldcpp_default.so" not found

### ISSUE THREAD

**Issue by NIEMONARCH** [LostRuins/koboldcpp#871]
When I put command ~/koboldcpp $ python koboldcpp.py --model KobbleTiny-Q4_K.gguf

I get an error *** Welcome to KoboldCpp - Version 1.66.1 Warning: OpenBLAS library file not found. Non-BLAS library will be used. Initializing dynamic library: koboldcpp_default.so Traceback (most recent call last): File "/data/data/com.termux/files/home/koboldcpp/koboldcpp.py", line 3540, in main(parser.parse_args(),start_server=True) File "/data/data/com.termux/files/home/koboldcpp/koboldcpp.py", line 3164, in main init_library() # Note: if blas does not exist and is enabled, program will crash. ^^^^^^^^^^^^^^ File "/data/data/com.termux/files/home/koboldcpp/koboldcpp.py", line 282, in init_library handle = ctypes.CDLL(os.path.join(dir_path, libname)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data/data/com.termux/files/usr/lib/python3.11/ctypes/init.py", line 376, in init self._handle = _dlopen(self._name, mode) ^^^^^^^^^^^^^^^^^^^^^^^^^ OSError: dlopen failed: library "/data/data/com.termux/files/home/koboldcpp/koboldcpp_default.so" not found

To run an AI ~/koboldcpp $ python koboldcpp.py --model KobbleTiny-Q4_K.gguf **

**Comment by LostRuins** [comment]
sounds like you're running koboldcpp from a directory that doesnt have sufficient permissions to read/execute from, or you did not perform the build steps correctly. Are you following the termux guide on the readme?.

**Comment by NIEMONARCH** [comment]
I retyped make Waited and it loaded fine

**Comment by NIEMONARCH** [comment]
I retype make, Waited and it works
