### ISSUE TITLE
Show this while loading

### ISSUE THREAD

**Issue by lolo17787** [LostRuins/koboldcpp#949]
***
Welcome to KoboldCpp - Version 1.68
For command line arguments, please refer to --help
***
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "subprocess.py", line 1370, in _readerthread
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 344: invalid continuation byte

**Comment by LostRuins** [comment]
Does it still load correctly?

**Comment by lolo17787** [comment]
> Does it still load correctly?

The model can be loaded normally, but I think the model is more stupid than the quality recommended by others.

**Comment by LostRuins** [comment]
What model are you trying to use?
